function spm5_devtool()
% 开发spm5 tool的工具
% Development tool for spm5's toolbox system
% -----------------------------------------------
% Copyright (C) 2008

% Ver: 20080910
% WadeFelix RenV, 2008-09-10


%% 主窗口
screenSize = get(0,'ScreenSize');
rvf = figure('Units','pixel','Position',[screenSize(3)/2-250 screenSize(4)/2-300 500 600],...
    'Name','Develop tool for SPM5 toolbox by renwei, LSRC (2008)', 'NumberTitle','off','resize','on','MenuBar', 'None','tag','UIconfigwindow'); 
%% 按钮
hp = uipanel(rvf,'Title','添加元件','FontSize',12,...
             'Position',[.05 .1 .3 .85],'tag','elementspanel');
elements = {'const','menu' ,'entry','files','branch' 'choice' 'repeat','job'};
h_elem = zeros(numel(elements),1);
for i = 1:numel(elements)
    h_elem(i) = uicontrol('Parent',hp,'String',elements{i},...
        'Units','normalized',...
        'Position',[.1 .1*i .8 .08],...
        'Callback',@cbk_h_elem,...
        'fontsize',12,...
        'tag',elements{i});
end
set(hp,'UserData',{h_elem,elements});

    function cbk_h_elem(hObj,Event)
        str = get(hObj,'tag');
        feval(['uipara_cfg_' str]);
        updatenodeinbox();
    end
%% 显示
h_rvbatch_box = uicontrol(rvf,'Style','listbox','Units','normalized','Position',[0.45 0.1 0.5 0.832],'Tag','rvbatch_box','fontsize',12);
helptext = {...
    '帮助:',...
    '1. 新建job',...
    '2. 添加各个节点',...
    '3. 点击“生成代码”按钮即生成一个lsrc_config_*.m文件。',...
    '4. 数据处理函数需要您自己动手编写，帮不了你了',...
    '其中',...
    'repeat - 重复容器，其子节点可按需求复制若干个;',...
    'choice - 选项容器，使用时只选择其某一个子节点;',...
    'branch - 束容器，可以包含若干个其他容器或项;',...
    'files  - 文件项，选择文件;',...
    'entry  - 输入项，输入字符串、数据值或矩阵;',...
    'menu   - 菜单项，单项选择菜单;',...
    'const  - 常量项.',...
    '此框上悬停即可出现此帮助',...
    '右键弹出删除菜单',...
    '',...
    'tag是什么?tag是spm生成该变量时变量的名字,',...
    '   所以请使用和显示名一样有意义的名字,且勿重复',...
    'by renwei.'};
set(h_rvbatch_box,'String',helptext,'TooltipString',sprintf('%s\n', helptext{:}));
cmenu = uicontextmenu;
uimenu(cmenu, 'Label', 'Delete', 'Callback', @cbk_delnode);
    function cbk_delnode(hObj,Event)
        h = findobj('Tag','rvbatch_box');
        node = get(h,'Value');
        nodescell = get(h,'UserData');
        if isempty(nodescell)
            return
        end
        nodescell = updatenodescell(nodescell,node,'del');
        set(h,'UserData',nodescell);
        updatenodeinbox();
    end
set(h_rvbatch_box,'UIContextMenu',cmenu);
%% 生成
h_btn = uicontrol('Style','pushbutton','Units','normalized','Position',[0.05 0.02 0.9 0.06],'String','生成代码','Callback',@cbk_copybtn,'fontsize',12);
% btn_help = {'点击即可生成内容并复制到系统剪贴板,新建m文件粘贴即可','但是处理数据的核心程序还劳你亲自动手啦'};
btn_help = {'点击即可生成文件','但是处理数据的核心程序还劳你亲自动手啦',['文件位于' fullfile(spm('Dir'),'toolbox')]};
set(h_btn,'TooltipString',sprintf('%s\n', btn_help{:}));

    function cbk_copybtn(hObj,Event)
        makecodes();
    end

%%
end
